if ![info exists PULP_FPGA_SIM] {
    set nvdla_RTL /home/vivi/pulp/rtl/nvdla
}






# nvdla
set NVDLA " \
    $nvdla_RTL/nvdla/apb2csb/NV_NVDLA_apb2csb.v \
    $nvdla_RTL/nvdla/bdma/NV_NVDLA_bdma.v\
    $nvdla_RTL/nvdla/bdma/NV_NVDLA_BDMA_cq.v\
$nvdla_RTL/nvdla/bdma/NV_NVDLA_BDMA_csb.v\
$nvdla_RTL/nvdla/bdma/NV_NVDLA_BDMA_gate.v\
$nvdla_RTL/nvdla/bdma/NV_NVDLA_BDMA_load.v\
$nvdla_RTL/nvdla/bdma/NV_NVDLA_BDMA_reg.v\
$nvdla_RTL/nvdla/bdma/NV_NVDLA_BDMA_store.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_cacc.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_assembly_buffer.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_assembly_ctrl.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_CALC_int8.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_calculator.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_delivery_buffer.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_delivery_ctrl.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_dual_reg.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_regfile.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_single_reg.v\
$nvdla_RTL/nvdla/cacc/NV_NVDLA_CACC_slcg.v\
$nvdla_RTL/nvdla/car/NV_NVDLA_core_reset.v\
$nvdla_RTL/nvdla/car/NV_NVDLA_reset.v\
$nvdla_RTL/nvdla/car/NV_NVDLA_ssync3d.v\
$nvdla_RTL/nvdla/car/NV_NVDLA_ssync3d_c.v\
$nvdla_RTL/nvdla/car/NV_NVDLA_sync3d.v\
$nvdla_RTL/nvdla/car/NV_NVDLA_sync3d_c.v\
$nvdla_RTL/nvdla/car/NV_NVDLA_sync3d_s.v\
$nvdla_RTL/nvdla/cbuf/NV_NVDLA_cbuf.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_cdma.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_cvt.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_CVT_cell.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_dc.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_DC_fifo.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_dma_mux.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_dual_reg.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_img.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_IMG_ctrl.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_IMG_fifo.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_IMG_pack.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg2pack_fifo.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_regfile.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_shared_buffer.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_single_reg.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_slcg.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_status.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_wg.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_WG_fifo.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_wt.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_WT_fifo.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_WT_sp_arb.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_WT_wgs_fifo.v\
$nvdla_RTL/nvdla/cdma/NV_NVDLA_CDMA_WT_wrr_arb.v\
$nvdla_RTL/nvdla/cdp/fp_format_cvt.v\
$nvdla_RTL/nvdla/cdp/fp_sum_block.v\
$nvdla_RTL/nvdla/cdp/int_sum_block.v\
$nvdla_RTL/nvdla/cdp/int_sum_block_tp1.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_cdp.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_dp.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin_tp1.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_cvtin.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_cvtout.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_intp.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_INTP_unit.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_lut.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_CTRL_unit.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_mul.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_MUL_unit.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_nan.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_sum.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_DP_syncfifo.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_rdma.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_RDMA_cq.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_RDMA_eg.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_RDMA_ig.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_RDMA_reg.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_dual.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_single.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_reg.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_REG_dual.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_REG_single.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_slcg.v\
$nvdla_RTL/nvdla/cdp/NV_NVDLA_CDP_wdma.v\
$nvdla_RTL/nvdla/cfgrom/NV_NVDLA_cfgrom.v\
$nvdla_RTL/nvdla/cfgrom/NV_NVDLA_CFGROM_rom.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_cmac.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_core.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_CORE_active.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_CORE_cfg.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_CORE_mac.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_in.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_out.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_CORE_slcg.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_reg.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_REG_dual.v\
$nvdla_RTL/nvdla/cmac/NV_NVDLA_CMAC_REG_single.v\
$nvdla_RTL/nvdla/csb_master/NV_NVDLA_csb_master.v\
$nvdla_RTL/nvdla/csb_master/NV_NVDLA_CSB_MASTER_csb2falcon_fifo.v\
$nvdla_RTL/nvdla/csb_master/NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_csc.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_dl.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_dual_reg.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_pra_cell.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_regfile.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_sg.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_SG_dat_fifo.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_SG_wt_fifo.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_single_reg.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_slcg.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_wl.v\
$nvdla_RTL/nvdla/csc/NV_NVDLA_CSC_WL_dec.v\
$nvdla_RTL/nvdla/glb/NV_NVDLA_glb.v\
$nvdla_RTL/nvdla/glb/NV_NVDLA_GLB_csb.v\
$nvdla_RTL/nvdla/glb/NV_NVDLA_GLB_CSB_reg.v\
$nvdla_RTL/nvdla/glb/NV_NVDLA_GLB_fc.v\
$nvdla_RTL/nvdla/glb/NV_NVDLA_GLB_ic.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_DMAIF_rdreq.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_DMAIF_rdrsp.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_DMAIF_wr.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_MCIF_csb.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_MCIF_CSB_reg.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_nocif.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_dram.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_read.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_cq.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_eg.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_ig.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_arb.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_bpt.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_cvt.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_spt.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_write.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_cq.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_eg.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_ig.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_arb.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_cvt.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_spt.v\
$nvdla_RTL/nvdla/nocif/NV_NVDLA_XXIF_libs.v\
$nvdla_RTL/nvdla/pdp/cal1d_fp16_pool_sum.v\
$nvdla_RTL/nvdla/pdp/fp16_4add.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_pdp.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_core.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_CORE_cal1d.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_CORE_cal2d.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_CORE_preproc.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_CORE_unit1d.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_nan.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_rdma.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_RDMA_cq.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_RDMA_eg.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_RDMA_ig.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_RDMA_reg.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_dual.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_single.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_reg.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_REG_dual.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_REG_single.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_slcg.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_wdma.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_WDMA_cmd.v\
$nvdla_RTL/nvdla/pdp/NV_NVDLA_PDP_WDMA_dat.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_cacc2glb.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_cmac_a2cacc.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_cmac_b2cacc.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_csb2cacc.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_csb2cmac.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_csc2cmac_a.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_csc2cmac_b.v\
$nvdla_RTL/nvdla/retiming/NV_NVDLA_RT_sdp2nocif.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_rubik.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_dma.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_dr2drc.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_dual_reg.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_fifo.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_intr.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_regfile.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_rf_core.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_rf_ctrl.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_rf_rcmd.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_rf_wcmd.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_seq_gen.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_single_reg.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_slcg.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_cmd.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_data.v\
$nvdla_RTL/nvdla/rubik/NV_NVDLA_RUBIK_wr_req.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_sdp.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_brdma.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_BRDMA_cq.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_BRDMA_gate.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_BRDMA_lat_fifo.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_cmux.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_core.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_CORE_gate.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_CORE_pack.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_CORE_unpack.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_CORE_y.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_lut.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_erdma.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_ERDMA_cq.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_ERDMA_gate.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_ERDMA_lat_fifo.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_c.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_C_int.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_lut_expn.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_lut_line.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_prelu.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_relu.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_sync2data.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_x1_int.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_x2_int.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_alu.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_mul.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_relu.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_trt.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_cvt_top.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_idx_top.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_inp_top.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_alu.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_core.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_cvt.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_idx.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_inp.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_mul.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_mrdma.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_MRDMA_cq.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_MRDMA_eg.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_cmd.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_din.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_dout.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_MRDMA_gate.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_MRDMA_ig.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_nrdma.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_NRDMA_cq.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_NRDMA_gate.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_NRDMA_lat_fifo.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_rdma.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_dmaif.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_eg.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_EG_ro.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_ig.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_pack.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_reg.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_dual.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_single.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_RDMA_unpack.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_reg.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_REG_dual.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_REG_single.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_wdma.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_WDMA_cmd.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_WDMA_dat.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_in.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_out.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_WDMA_gate.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_WDMA_intr.v\
$nvdla_RTL/nvdla/sdp/NV_NVDLA_SDP_WDMA_unpack.v\
$nvdla_RTL/nvdla/top/NV_nvdla.v\
$nvdla_RTL/nvdla/top/NV_NVDLA_partition_a.v\
$nvdla_RTL/nvdla/top/NV_NVDLA_partition_c.v\
$nvdla_RTL/nvdla/top/NV_NVDLA_partition_m.v\
$nvdla_RTL/nvdla/top/NV_NVDLA_partition_o.v\
$nvdla_RTL/nvdla/top/NV_NVDLA_partition_p.v\
$nvdla_RTL/nvdla/top/NV_nvdlawarapper.v\
    
"
set INC_NVDLA " \
    $nvdla_RTL/includes/NV_HWACC_NVDLA_tick_defines.vh\
$nvdla_RTL/includes/simulate_x_tick.vh\
$nvdla_RTL/vlibs/assertion_header.vh\
$nvdla_RTL/vlibs/assertion_task.vh\
"
set NVDLA_RAMS " \
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_16x64.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_16x256.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_16x272.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_32x16.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_32x512.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_32x544.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_32x768.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_64x10.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_64x18.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_64x116.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_64x1024.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_64x1088.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_128x18.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_128x64.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_128x256.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_256x3.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_256x7.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_256x64.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_256x512.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_512x64.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_512x256.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rws_512x512.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_8x65.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_20x289.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_32x32.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_61x64.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_61x65.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_61x514.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_80x14.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_80x16.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_80x65.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_80x256.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_80x514.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_128x6.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_128x11.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_160x16.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_160x65.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_160x514.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_245x514.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsp_256x11.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwst_256x8.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_19x4.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_19x32.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_19x80.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_60x21.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_60x168.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_80x9.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_80x15.v\
$nvdla_RTL/rams/fpga/small_rams/nv_ram_rwsthp_80x72.v\

"
set NVDLA_VLIBS "\
$nvdla_RTL/vlibs/AN2D4PO4.v\
$nvdla_RTL/vlibs/CKLNQD12.v\
$nvdla_RTL/vlibs/CKLNQD12PO4.v\
$nvdla_RTL/vlibs/HLS_cdp_icvt.v\
$nvdla_RTL/vlibs/HLS_cdp_ocvt.v\
$nvdla_RTL/vlibs/HLS_fp16_to_fp17.v\
$nvdla_RTL/vlibs/HLS_fp16_to_fp32.v\
$nvdla_RTL/vlibs/HLS_fp17_add.v\
$nvdla_RTL/vlibs/HLS_fp17_mul.v\
$nvdla_RTL/vlibs/HLS_fp17_sub.v\
$nvdla_RTL/vlibs/HLS_fp17_to_fp16.v\
$nvdla_RTL/vlibs/HLS_fp17_to_fp32.v\
$nvdla_RTL/vlibs/HLS_fp32_add.v\
$nvdla_RTL/vlibs/HLS_fp32_mul.v\
$nvdla_RTL/vlibs/HLS_fp32_sub.v\
$nvdla_RTL/vlibs/HLS_fp32_to_fp16.v\
$nvdla_RTL/vlibs/HLS_fp32_to_fp17.v\
$nvdla_RTL/vlibs/HLS_uint16_to_fp17.v\
$nvdla_RTL/vlibs/LNQD1PO4.v\
$nvdla_RTL/vlibs/MUX2D4.v\
$nvdla_RTL/vlibs/MUX2HDD2.v\
$nvdla_RTL/vlibs/NV_BLKBOX_BUFFER.v\
$nvdla_RTL/vlibs/NV_BLKBOX_SINK.v\
$nvdla_RTL/vlibs/NV_BLKBOX_SRC0.v\
$nvdla_RTL/vlibs/NV_BLKBOX_SRC0_X.v\
$nvdla_RTL/vlibs/NV_CLK_gate_power.v\
$nvdla_RTL/vlibs/NV_DW02_tree.v\
$nvdla_RTL/vlibs/NV_DW_lsd.v\
$nvdla_RTL/vlibs/NV_DW_minmax.v\
$nvdla_RTL/vlibs/NV_NVDLA_CDP_HLS_icvt.v\
$nvdla_RTL/vlibs/NV_NVDLA_CDP_HLS_ocvt.v\
$nvdla_RTL/vlibs/NV_NVDLA_HLS_saturate.v\
$nvdla_RTL/vlibs/NV_NVDLA_HLS_shiftleftsu.v\
$nvdla_RTL/vlibs/NV_NVDLA_HLS_shiftrightsatsu.v\
$nvdla_RTL/vlibs/NV_NVDLA_HLS_shiftrightss.v\
$nvdla_RTL/vlibs/NV_NVDLA_HLS_shiftrightsu.v\
$nvdla_RTL/vlibs/NV_NVDLA_HLS_shiftrightusz.v\
$nvdla_RTL/vlibs/oneHotClk_async_read_clock.v\
$nvdla_RTL/vlibs/oneHotClk_async_write_clock.v\
$nvdla_RTL/vlibs/OR2D1.v\
$nvdla_RTL/vlibs/PGAOPV_AN2D2PO4.v\
$nvdla_RTL/vlibs/PGAOPV_DFCNQD2PO4.v\
$nvdla_RTL/vlibs/PGAOPV_INVD2PO4.v\
$nvdla_RTL/vlibs/p_SDFCNQD1PO4.v\
$nvdla_RTL/vlibs/p_SSYNC2DO_C_PP.v\
$nvdla_RTL/vlibs/p_SSYNC3DO.v\
$nvdla_RTL/vlibs/p_SSYNC3DO_C_PPP.v\
$nvdla_RTL/vlibs/p_SSYNC3DO_S_PPP.v\
$nvdla_RTL/vlibs/p_STRICTSYNC3DOTM_C_PPP.v\
$nvdla_RTL/vlibs/ScanShareSel_JTAG_reg_ext_cg.v\
$nvdla_RTL/vlibs/SDFCNQD1.v\
$nvdla_RTL/vlibs/SDFQD1.v\
$nvdla_RTL/vlibs/SDFSNQD1.v\
$nvdla_RTL/vlibs/sync2d_c_pp.v\
$nvdla_RTL/vlibs/sync3d.v\
$nvdla_RTL/vlibs/sync3d_c_ppp.v\
$nvdla_RTL/vlibs/sync3d_s_ppp.v\
$nvdla_RTL/vlibs/sync_reset.v\

"
